#!/bin/bash


SCRIPTS="${PWD}/sd_report_zones/sd_report_zones"
SCRIPTS="${SCRIPTS} ${PWD}/sd_reset_wp/sd_zone_close"
SCRIPTS="${SCRIPTS} ${PWD}/sd_reset_wp/sd_zone_finish"
SCRIPTS="${SCRIPTS} ${PWD}/sd_reset_wp/sd_zone_open"
SCRIPTS="${SCRIPTS} ${PWD}/sd_reset_wp/sd_reset_wp"

INSTALL_TO="${HOME}/bin"

if [[ ! -d ${INSTALL_TO} ]]; then
	echo ${INSTALL_TO} not found. Creating.
	mkdir ${INSTALL_TO}
fi

if [[ -d ${INSTALL_TO} ]]; then
	echo Installing to ${INSTALL_TO} ...
	cd ${INSTALL_TO}
fi

echo Installing scripts to ${INSTALL_TO}
for i in ${SCRIPTS}
do
	echo ln -sf ${i} ~/bin/.
	ln -sf ${i} .
done
